EPS = 1e-6

CANNY_LOW_THRESH = 0.1
CANNY_HIGH_THRESH = 0.3
CANNY_SIGMA = 1.2

SALIENCY_THRESH = 0.3
MIN_NON_EDGE_AREA = 400

HIST_SHIFT_BIN_RATIO = 0.05
SIFT_EDGE_THRESH = 500
SIFT_RATIO_THRESH = 0.75
RANSAC_REPROJ_THRESH = 1.5

GC_SALIENCY_WEIGHT = 3.0
GC_OBJECT_WEIGHT = 4.0
GC_EDGE_PENALTY = 5.0
GC_MODE = "normal"

SEAM_SOFT_BAND = 20
SEAM_POISSON_BAND = 3

PYRAMID_LEVELS = 6

TRANSITION_KERNEL_SIZE = 9

EXPOSURE_MIN_PIXELS = 100
EXPOSURE_EPS = 1e-6
EXPOSURE_MIN_GAIN = 0.5
EXPOSURE_MAX_GAIN = 2.0
EXPOSURE_TRANSITION_KERNEL_SIZE = 23
EXPOSURE_ADJUSTMENT_STRENGTH = 0.95

SEAM_BAND = 9
FEATHER_RADIUS = 11

DEFAULT_PIPELINE_CONFIG = {
    "CANNY_LOW_THRESH": CANNY_LOW_THRESH,
    "CANNY_HIGH_THRESH": CANNY_HIGH_THRESH,
    "CANNY_SIGMA": CANNY_SIGMA,

    "SIFT_EDGE_THRESH": SIFT_EDGE_THRESH,
    "SIFT_RATIO_THRESH": SIFT_RATIO_THRESH,
    "HIST_SHIFT_BIN_RATIO": HIST_SHIFT_BIN_RATIO,
    "RANSAC_REPROJ_THRESH": RANSAC_REPROJ_THRESH,

    "GC_SALIENCY_WEIGHT": GC_SALIENCY_WEIGHT,
    "GC_OBJECT_WEIGHT": GC_OBJECT_WEIGHT,
    "GC_EDGE_PENALTY": GC_EDGE_PENALTY,
    "GC_MODE": GC_MODE,

    "SEAM_BAND": SEAM_BAND,
    "FEATHER_RADIUS": FEATHER_RADIUS,
}
