EPS = 1e-6

CANNY_LOW_THRESH = 0.1
CANNY_HIGH_THRESH = 0.3
CANNY_SIGMA = 1.2

SALIENCY_THRESH = 0.3
MIN_NON_EDGE_AREA = 400

HIST_SHIFT_BIN_RATIO = 0.05
# 重命名：SIFT_RATIO_THRESH -> FEATURE_RATIO_THRESH，因为它被所有检测器使用
FEATURE_RATIO_THRESH = 0.75
RANSAC_REPROJ_THRESH = 1.5

GC_SALIENCY_WEIGHT = 3.0
GC_OBJECT_WEIGHT = 4.0
GC_EDGE_PENALTY = 5.0

SEAM_SOFT_BAND = 20
SEAM_POISSON_BAND = 3

PYRAMID_LEVELS = 6

TRANSITION_KERNEL_SIZE = 9

EXPOSURE_MIN_PIXELS = 100
EXPOSURE_EPS = 1e-6
EXPOSURE_MIN_GAIN = 0.5
EXPOSURE_MAX_GAIN = 2.0
EXPOSURE_TRANSITION_KERNEL_SIZE = 23
EXPOSURE_ADJUSTMENT_STRENGTH = 0.95

SEAM_BAND = 9
FEATHER_RADIUS = 11

FEATURE_DETECTOR = 'ORB'
FEATURE_NPOINTS = 2000
FEATURE_EDGE_THRESH = 31
FEATURE_FIRST_LEVEL = 0
FEATURE_N_OCTAVE_LAYERS = 3
FEATURE_PATCH_SIZE = 31
# SIFT特定参数
SIFT_EDGE_THRESH = 500

FLANN_INDEX_PARAMS = {'algorithm': 6, 'table_number': 6, 'key_size': 12, 'multi_probe_level': 1}
FLANN_SEARCH_PARAMS = {'checks': 50}
USE_FLANN = True
